# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Login_Menu(object):
    def setupUi(self, Login_Menu):
        Login_Menu.setObjectName("Login_Menu")
        Login_Menu.resize(422, 614)
        Login_Menu.setMinimumSize(QtCore.QSize(422, 614))
        Login_Menu.setMaximumSize(QtCore.QSize(422, 614))
        self.centralwidget = QtWidgets.QWidget(Login_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(13, 18, 48);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.text_donthaveaccount = QtWidgets.QLabel(self.dropShadowFrame)
        self.text_donthaveaccount.setGeometry(QtCore.QRect(0, 550, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_donthaveaccount.setFont(font)
        self.text_donthaveaccount.setStyleSheet("color: rgb(130, 127, 148);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 25 5pt \"Segoe UI Light\";")
        self.text_donthaveaccount.setAlignment(QtCore.Qt.AlignCenter)
        self.text_donthaveaccount.setObjectName("text_donthaveaccount")
        self.button_login = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_login.setEnabled(True)
        self.button_login.setGeometry(QtCore.QRect(70, 370, 261, 41))
        self.button_login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_login.setMouseTracking(False)
        self.button_login.setToolTip("")
        self.button_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_login.setAutoFillBackground(False)
        self.button_login.setStyleSheet("QPushButton {\n"
"    background-color: rgb(93, 97, 117);\n"
"    color: rgb(208, 208, 208);\n"
"    font: 12pt \"Segoe UI\";\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(55, 52, 70);\n"
"\n"
"}")
        self.button_login.setCheckable(False)
        self.button_login.setAutoRepeat(False)
        self.button_login.setAutoExclusive(False)
        self.button_login.setDefault(True)
        self.button_login.setObjectName("button_login")
        self.text_password = QtWidgets.QLineEdit(self.dropShadowFrame)
        self.text_password.setEnabled(True)
        self.text_password.setGeometry(QtCore.QRect(90, 310, 221, 21))
        self.text_password.setAcceptDrops(True)
        self.text_password.setAutoFillBackground(False)
        self.text_password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.text_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.text_password.setInputMask("")
        self.text_password.setText("")
        self.text_password.setFrame(False)
        self.text_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_password.setAlignment(QtCore.Qt.AlignCenter)
        self.text_password.setDragEnabled(False)
        self.text_password.setReadOnly(False)
        self.text_password.setClearButtonEnabled(True)
        self.text_password.setObjectName("text_password")
        self.text_forgot = QtWidgets.QLabel(self.dropShadowFrame)
        self.text_forgot.setGeometry(QtCore.QRect(0, 420, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.text_forgot.setFont(font)
        self.text_forgot.setStyleSheet("\n"
"color: rgb(130, 127, 148);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 25 5pt \"Segoe UI Light\";")
        self.text_forgot.setAlignment(QtCore.Qt.AlignCenter)
        self.text_forgot.setObjectName("text_forgot")
        self.line_password = QtWidgets.QFrame(self.dropShadowFrame)
        self.line_password.setGeometry(QtCore.QRect(62, 340, 280, 1))
        self.line_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_password.setStyleSheet("background-color: rgb(130, 127, 148);")
        self.line_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_password.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_password.setObjectName("line_password")
        self.line_username = QtWidgets.QFrame(self.dropShadowFrame)
        self.line_username.setGeometry(QtCore.QRect(62, 290, 280, 1))
        self.line_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_username.setStyleSheet("background-color: rgb(130, 127, 148);")
        self.line_username.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_username.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_username.setObjectName("line_username")
        self.text_username = QtWidgets.QLineEdit(self.dropShadowFrame)
        self.text_username.setEnabled(True)
        self.text_username.setGeometry(QtCore.QRect(90, 260, 221, 21))
        self.text_username.setAcceptDrops(True)
        self.text_username.setAutoFillBackground(False)
        self.text_username.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(208, 208, 208);\n"
"font: 25 12pt \"Segoe UI Light\";")
        self.text_username.setInputMethodHints(QtCore.Qt.ImhNone)
        self.text_username.setInputMask("")
        self.text_username.setText("")
        self.text_username.setFrame(False)
        self.text_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.text_username.setAlignment(QtCore.Qt.AlignCenter)
        self.text_username.setDragEnabled(False)
        self.text_username.setReadOnly(False)
        self.text_username.setClearButtonEnabled(False)
        self.text_username.setObjectName("text_username")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.dropShadowFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 401, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_Logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img_Logo.setFocusPolicy(QtCore.Qt.TabFocus)
        self.img_Logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_Logo.setStyleSheet("background-image: url(:/NewLogo/img/logo.png);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.img_Logo.setText("")
        self.img_Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.img_Logo.setObjectName("img_Logo")
        self.horizontalLayout.addWidget(self.img_Logo)
        self.icon_user = QtWidgets.QLabel(self.dropShadowFrame)
        self.icon_user.setGeometry(QtCore.QRect(40, 260, 61, 21))
        self.icon_user.setStyleSheet("image: url(:/User/img/user.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.icon_user.setText("")
        self.icon_user.setObjectName("icon_user")
        self.icon_lock = QtWidgets.QLabel(self.dropShadowFrame)
        self.icon_lock.setGeometry(QtCore.QRect(40, 310, 61, 21))
        self.icon_lock.setStyleSheet("image: url(:/Lock/img/lock.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.icon_lock.setText("")
        self.icon_lock.setObjectName("icon_lock")
        self.button_close = QtWidgets.QPushButton(self.dropShadowFrame)
        self.button_close.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.button_close.setStyleSheet("QPushButton {\n"
"   border:none;\n"
"   border-radius:8px;\n"
"       background-color: rgb(93, 97, 117);\n"
"   color: rgb(208, 208, 208);\n"
"   font: 6pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(55, 52, 70);\n"
"\n"
"\n"
"}")
        self.button_close.setAutoDefault(True)
        self.button_close.setObjectName("button_close")
        self.frame_error = QtWidgets.QFrame(self.dropShadowFrame)
        self.frame_error.setGeometry(QtCore.QRect(60, 450, 311, 41))
        self.frame_error.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setGeometry(QtCore.QRect(10, 0, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_error.setFont(font)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.button_close_popup = QtWidgets.QPushButton(self.frame_error)
        self.button_close_popup.setGeometry(QtCore.QRect(280, 10, 21, 21))
        self.button_close_popup.setStyleSheet("QPushButton {\n"
"   border:none;\n"
"   border-radius:8px;\n"
"       background-color: rgb(93, 97, 117);\n"
"   color: rgb(208, 208, 208);\n"
"   font: 6pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(55, 52, 70);\n"
"\n"
"\n"
"}")
        self.button_close_popup.setAutoDefault(True)
        self.button_close_popup.setObjectName("button_close_popup")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        Login_Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Menu)
        QtCore.QMetaObject.connectSlotsByName(Login_Menu)
        Login_Menu.setTabOrder(self.img_Logo, self.text_username)
        Login_Menu.setTabOrder(self.text_username, self.text_password)
        Login_Menu.setTabOrder(self.text_password, self.button_login)
        Login_Menu.setTabOrder(self.button_login, self.button_close_popup)
        Login_Menu.setTabOrder(self.button_close_popup, self.button_close)

    def retranslateUi(self, Login_Menu):
        _translate = QtCore.QCoreApplication.translate
        Login_Menu.setWindowTitle(_translate("Login_Menu", "MainWindow"))
        self.text_donthaveaccount.setText(_translate("Login_Menu", "<html><head/><body><p><span style=\" font-size:11pt;\">Don\'t have an account? </span><span style=\" font-size:11pt; font-weight:600;\">Create one</span></p></body></html>"))
        self.button_login.setText(_translate("Login_Menu", "Log In"))
        self.text_password.setPlaceholderText(_translate("Login_Menu", "Password"))
        self.text_forgot.setWhatsThis(_translate("Login_Menu", "<html><head/><body><p>Forgot your <span style=\" font-weight:600;\">password?</span></p></body></html>"))
        self.text_forgot.setText(_translate("Login_Menu", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:400;\">Forgot your password?</span></p></body></html>"))
        self.text_username.setPlaceholderText(_translate("Login_Menu", "Email"))
        self.button_close.setText(_translate("Login_Menu", "X"))
        self.label_error.setText(_translate("Login_Menu", "Email or Password incorrect"))
        self.button_close_popup.setText(_translate("Login_Menu", "X"))
import rc_login


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Menu = QtWidgets.QMainWindow()
    ui = Ui_Login_Menu()
    ui.setupUi(Login_Menu)
    Login_Menu.show()
    sys.exit(app.exec_())
